image: Ubuntu

stack: jdk 11

branches:
  only:
    - master
    - validation

build: off

install:
  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info